const services = [
  {group:'Psicoterapia',items:[
    {slug:'psicoterapia-adultos',title:'Psicoterapia para adultos',short:'Cuidado psicológico para diferentes momentos, dificuldades e mudanças da vida adulta.',mode:'Presencial em Taquara ou online'},
    {slug:'psicoterapia-criancas-adolescentes',title:'Psicoterapia para crianças e adolescentes',short:'Um processo adequado à idade, com atividades e participação dos responsáveis ao longo do acompanhamento.',mode:'Presencial a partir de 3 anos · online a partir de 10 anos'}]},
  {group:'Avaliação neuropsicológica',items:[
    {slug:'avaliacao-adultos',title:'Avaliação de adultos',short:'Investigação individualizada da atenção, memória, raciocínio, emoções e funcionamento cotidiano.',mode:'Presencial ou online'},
    {slug:'avaliacao-criancas-adolescentes',title:'Avaliação de crianças e adolescentes',short:'Investigação para compreender desenvolvimento, aprendizagem, atenção, memória, emoções e comportamento.',mode:'Presencial'},
    {slug:'avaliacao-bebes-criancas-pequenas',title:'Avaliação de bebês e crianças pequenas',short:'Avaliação do desenvolvimento, incluindo linguagem, motricidade, interação, cognição, emoções e comportamento.',mode:'Presencial'}]},
  {group:'TDAH, autismo e autonomia',items:[
    {slug:'acompanhamento-tdah',title:'Psicoterapia para pessoas com TDAH',short:'Cuidado especializado, com conhecimento sobre o TDAH e seus impactos emocionais, relacionais e no dia a dia.',mode:'Psicoterapia individual'},
    {slug:'acompanhamento-autismo',title:'Psicoterapia para pessoas autistas',short:'Cuidado especializado que considera emoções, relações, identidade, sobrecarga, rotina e necessidades de adaptação.',mode:'Presencial ou online'},
    {slug:'organizacao-planejamento-autonomia',title:'Organização e Planejamento para Adultos com TDAH',short:'Uma intervenção individual de 12 semanas com apoio profissional para compreender dificuldades e aplicar estratégias de tempo, organização e planejamento à vida real.',mode:'Exclusivo para adultos com TDAH'}]},
  {group:'Escolhas e mudanças',items:[
    {slug:'orientacao-profissional-carreira',title:'Orientação profissional e de carreira',short:'Apoio especializado para escolhas, mudanças e transições relacionadas aos estudos, à profissão, à carreira e à aposentadoria.',mode:'Adolescentes e adultos'}]}
];

const reimbursement = 'Os atendimentos são particulares e não sou credenciada a convênios. Quando o plano oferece reembolso, forneço a documentação necessária para a solicitação. O valor e as condições dependem das regras de cada convênio.';
const adultTherapyPricing = {eyebrow:'Valores da psicoterapia',title:'Frequência e investimento',intro:'Os valores são os mesmos para atendimento presencial e online.',options:[['Sessões com frequência semanal','R$ 170 por sessão','Pix ou cartão.'],['Sessão avulsa','R$ 200','Pix ou cartão.']],reimbursement};
const childTherapyPricing = {eyebrow:'Valores da psicoterapia',title:'Frequência e investimento',intro:'Os valores são os mesmos para atendimento presencial e online.',options:[['Sessões com frequência semanal','R$ 170 por sessão','Pix ou cartão.'],['Consulta pontual com responsáveis','R$ 200','Pix ou cartão. Disponível quando não se trata do início do acompanhamento da criança ou do adolescente.']],reimbursement,note:'Não é oferecida sessão avulsa de psicoterapia para a criança ou o adolescente.'};
const specializedTherapyPricing = {eyebrow:'Valores da psicoterapia',title:'Frequência e investimento',intro:'Os valores são os mesmos para atendimento presencial e online.',options:[['Sessões com frequência semanal','R$ 170 por sessão','Pix ou cartão.'],['Sessão avulsa','R$ 200','Pix ou cartão.']],reimbursement};
const assessmentPricing = {eyebrow:'Investimento',title:'Valores da avaliação',intro:'Os honorários da avaliação são de R$ 2.300. Escolha a condição de pagamento mais adequada para você.',options:[['Pagamento integral','1 x R$ 2.300 = R$ 2.300','Pagamento integral no início da avaliação.'],['Pagamento por sessão','10 x R$ 230 = R$ 2.300','Pagamento realizado a cada sessão.'],['Pagamento em duas etapas','2 x R$ 1.150 = R$ 2.300','Uma parcela no início e outra no final.'],['Parcelamento no cartão','6 x R$ 400 = R$ 2.400','O valor considera os custos dessa modalidade de pagamento.']],reimbursement};
const earlyAssessmentPricing = {eyebrow:'Investimento',title:'Valor da avaliação',intro:'O valor inclui o processo de avaliação e a devolutiva.',options:[['Parcelamento','6 x R$ 340 = R$ 2.040','Valor total de R$ 2.040.']],reimbursement};
const programPricing = {eyebrow:'Investimento',title:'Investimento na intervenção',intro:'O investimento contempla as 12 semanas de atendimento, com 12 encontros individuais e os materiais utilizados ao longo do processo.',options:[['Intervenção completa','6 x R$ 400 = R$ 2.400','Doze encontros individuais de 50 minutos.']],reimbursement};
const careerPricing = {eyebrow:'Investimento',title:'Um processo definido conforme a sua necessidade',intro:'O processo é realizado em três a cinco encontros, conforme a questão que você precisa trabalhar e os objetivos definidos.',options:[['Valor por encontro','R$ 200','O valor total pode ser parcelado no cartão em até 6 vezes.']],note:'Entre em contato pelo WhatsApp para conversar sobre o que você procura e receber uma estimativa do número de encontros e do investimento total.'};

const adultTherapyCare = [
  ['Escuta especializada','Um espaço de escuta profissional para compreender o que você está vivendo, suas dificuldades, experiências, emoções e necessidades.'],
  ['Acolhimento sem julgamentos','Um espaço em que você pode falar com liberdade, inclusive sobre assuntos difíceis, contraditórios ou que tenha receio de compartilhar com outras pessoas.'],
  ['Sigilo profissional','O que você compartilha durante o acompanhamento é protegido pelo sigilo profissional, conforme previsto para o exercício da Psicologia.'],
  ['Compreensão do seu caso','Desde o início, buscamos juntos compreender sua história, o momento atual, os contextos em que você vive e como pensamentos, emoções, comportamentos e relações se conectam às dificuldades e mudanças que deseja construir.'],
  ['Intervenções psicológicas','As sessões não se limitam à conversa. Utilizo intervenções psicológicas adequadas às suas necessidades e aos objetivos construídos para o acompanhamento.'],
  ['Objetivos e acompanhamento da evolução','Definimos juntos o que precisa ser priorizado. Ao longo do processo, observamos o que está mudando, o que continua difícil e o que precisa ser ajustado ou aprofundado.'],
  ['Estratégias para o cotidiano','Quando necessário, construímos estratégias para lidar com situações, emoções, comportamentos, relações ou dificuldades práticas da vida cotidiana.'],
  ['Atividades e materiais entre as sessões','Exercícios, registros, leituras, materiais ou experiências práticas podem ser propostos quando ajudarem a dar continuidade ao trabalho fora da sessão.'],
  ['Testes, escalas e outros instrumentos','Quando forem úteis para compreender melhor alguma questão, podem ser utilizados testes, escalas, questionários e outros instrumentos psicológicos pertinentes.'],
  ['Orientações e psicoeducação','Você pode receber informações e orientações para compreender melhor emoções, comportamentos, padrões, sintomas, diagnósticos e outras questões relacionadas ao acompanhamento.'],
  ['Encaminhamentos e integração com outros cuidados','Quando necessário e com sua autorização, posso orientar encaminhamentos ou me comunicar com médicos e outros profissionais envolvidos no seu cuidado.'],
  ['Documentos psicológicos','Quando houver necessidade e indicação, podem ser elaborados documentos psicológicos relacionados ao acompanhamento e à sua finalidade.']
];
const childTherapyCare = [
  ['Escuta e acolhimento adequados à idade','Um espaço seguro para que a criança ou adolescente possa se expressar e ser compreendido de uma forma adequada ao seu desenvolvimento.'],
  ['Sigilo e respeito à privacidade','O acompanhamento preserva o espaço próprio da criança ou adolescente, respeitando o sigilo profissional e considerando a participação necessária dos responsáveis.'],
  ['Compreensão do caso','A história, o desenvolvimento, as emoções, os comportamentos, as relações e as dificuldades em diferentes contextos são considerados para compreender o que está acontecendo.'],
  ['Intervenções psicológicas','As intervenções são escolhidas de acordo com a idade, as necessidades e os objetivos do acompanhamento.'],
  ['Atividades, jogos e recursos terapêuticos','Jogos, atividades, histórias, desenhos e outros recursos podem facilitar a expressão e o trabalho terapêutico.'],
  ['Objetivos e acompanhamento da evolução','O processo tem objetivos que orientam o trabalho e podem ser revistos conforme as mudanças e necessidades observadas.'],
  ['Orientação aos responsáveis','Os responsáveis recebem orientações para compreender melhor as dificuldades e apoiar no cotidiano o que está sendo trabalhado.'],
  ['Comunicação com os responsáveis','O contato ao longo do acompanhamento permite compartilhar informações relevantes sobre evolução, dificuldades e necessidades.'],
  ['Estratégias e atividades para casa','Quando pertinente, podem ser propostas estratégias ou atividades para ajudar a levar as mudanças para o cotidiano.'],
  ['Testes, escalas e outros instrumentos','Instrumentos psicológicos podem ser utilizados quando ajudarem a compreender melhor alguma questão clínica.'],
  ['Contato com escola e outros profissionais','Quando necessário e autorizado pelos responsáveis, podem ocorrer trocas com a escola, médicos ou outros profissionais envolvidos.'],
  ['Documentos psicológicos','Podem ser elaborados quando houver indicação e finalidade pertinente.']
];
const tdahTherapyCare = [...adultTherapyCare,
  ['Compreensão de como o TDAH aparece na sua vida','O diagnóstico é considerado junto à sua história, emoções, relações, autoestima, rotina e demais aspectos da sua vida.'],
  ['Psicoeducação sobre TDAH','Informações sobre o transtorno podem ajudar a compreender dificuldades, reconhecer padrões e encontrar formas mais adequadas de lidar com eles.'],
  ['Estratégias para dificuldades executivas','Quando necessário, o acompanhamento também pode incluir estratégias para dificuldades de organização, planejamento, manejo do tempo, início de tarefas e outras funções executivas.']
];
const autismTherapyCare = [...adultTherapyCare,
  ['Compreensão do seu funcionamento individual','A psicoterapia considera sua história, características, necessidades, formas de perceber e responder às situações e o contexto em que você vive.'],
  ['Respeito às características autistas e à sua autonomia','O objetivo não é ensinar uma forma “normal” de funcionar, mas construir mudanças coerentes com suas necessidades, valores e autonomia.'],
  ['Compreensão de sobrecargas e necessidades de adaptação','Quando essas questões estiverem presentes, o acompanhamento pode ajudar a identificar fontes de sobrecarga, limites e adaptações que façam sentido para sua vida.'],
  ['Estratégias práticas quando necessárias','Estratégias relacionadas à rotina, comunicação, organização, relações ou outras dificuldades podem fazer parte da psicoterapia quando forem úteis.']
];

const adultTherapyPrinciples = [
  ['A pessoa vem antes da abordagem','Procuro compreender sua história, seu momento atual, seu contexto, suas relações, seus objetivos e seus valores antes de escolher os recursos do trabalho. As abordagens e técnicas são recursos para ajudar, não modelos aos quais você precisa se adaptar.'],
  ['O presente importa sem apagar a história','O que está produzindo sofrimento ou dificultando sua vida hoje merece atenção. A história também é considerada quando ajuda a compreender como determinadas formas de sentir, pensar, agir e se relacionar foram construídas.'],
  ['Direção e respeito ao tempo caminham juntos','Participo ativamente do processo e acompanho os objetivos construídos com você. Isso não significa apressar mudanças nem decidir por você. Buscamos passos possíveis que ampliem sua autonomia e aproximem você da vida que deseja construir.'],
  ['Nem tudo é explicado apenas pelo psicológico','Aspectos físicos, cognitivos, sociais, relacionais, ambientais e ligados ao momento de vida podem participar do que você está vivendo. Quando necessário, reconheço os limites da Psicologia e considero outros cuidados.']
];

const childTherapyPrinciples = [
  ['Direção com respeito ao desenvolvimento','O acompanhamento tem objetivos construídos com a família e revistos ao longo do processo. As mudanças são cuidadas sem desconsiderar o tempo, os limites e as possibilidades da criança ou do adolescente.'],
  ['A criança é compreendida em seu contexto','Aspectos emocionais, físicos, cognitivos, familiares, escolares, sociais e ambientais podem estar relacionados ao que está acontecendo. A participação dos responsáveis e, quando necessário e autorizado, o diálogo com a escola e outros profissionais ajudam a integrar o cuidado.']
];

const tdahTherapyPrinciples = [
  ['A pessoa vem antes da abordagem','O conhecimento sobre TDAH orienta o trabalho, mas a psicoterapia parte da sua história, do seu funcionamento, das suas relações, dos seus objetivos e da vida que deseja construir.'],
  ['Compreender a dificuldade torna a mudança possível','Saber o que deveria ser feito nem sempre é suficiente para conseguir transformar intenção em ação. Procuramos compreender o que dificulta a mudança antes de construir estratégias possíveis para a sua realidade.'],
  ['Direção e respeito ao tempo caminham juntos','Participo ativamente do processo e acompanho os objetivos construídos com você. O trabalho integra questões emocionais e relacionais com recursos práticos, sem apressar mudanças nem decidir por você.'],
  ['As dificuldades são compreendidas de forma integrada','Nem toda dificuldade de atenção, organização ou regulação emocional é explicada apenas pelo TDAH ou pelo psicológico. Outros aspectos da saúde, do ambiente, das relações e do momento de vida também são considerados.']
];

const autismTherapyPrinciples = [
  ['A pessoa vem antes da abordagem','O conhecimento sobre autismo orienta o trabalho, mas a psicoterapia parte da sua história, das suas características, das suas relações, dos seus valores e da vida que deseja construir.'],
  ['Valores e autonomia orientam o processo','Os objetivos são construídos considerando aquilo que faz sentido para a pessoa, suas necessidades e a vida que deseja construir. O trabalho não busca impor uma forma única de viver ou funcionar.'],
  ['Direção e respeito ao tempo caminham juntos','Participo ativamente do processo e acompanho os objetivos construídos com você. O trabalho pode integrar questões emocionais e relacionais com estratégias práticas, sem impor uma forma única de viver ou funcionar.'],
  ['As necessidades são compreendidas de forma integrada','Sobrecarga, comunicação, rotina, autonomia e relações podem ser influenciadas por aspectos emocionais, físicos, sensoriais, sociais e ambientais. Quando necessário, outros cuidados também são considerados.']
];
const adultAssessmentCare = [
  ['Entrevista clínica detalhada','Investigação da sua história, dificuldades atuais, funcionamento cotidiano e questões que precisam ser respondidas pela avaliação.'],
  ['Avaliação planejada para o seu caso','Os procedimentos e instrumentos são selecionados conforme as perguntas da avaliação, em vez de utilizar a mesma bateria para todas as pessoas.'],
  ['Testes psicológicos e neuropsicológicos','São utilizados instrumentos adequados para investigar as funções e questões relevantes para o caso.'],
  ['Investigação cognitiva, emocional e comportamental','Conforme a necessidade, são considerados aspectos como atenção, memória, raciocínio, funções executivas, emoções, comportamento e personalidade.'],
  ['Integração de diferentes informações','Entrevistas, testes, observação clínica, questionários e documentos anteriores são analisados em conjunto quando pertinentes.'],
  ['Análise clínica individualizada','Os resultados são relacionados entre si, à sua história e ao funcionamento na vida cotidiana.'],
  ['Investigação de hipóteses diagnósticas','Quando essa for uma das perguntas da avaliação, as informações são analisadas para esclarecer hipóteses e realizar diagnóstico diferencial.'],
  ['Laudo neuropsicológico','Você recebe um laudo com a integração dos resultados, conclusões e recomendações pertinentes, escrito de forma compreensível.'],
  ['Sessão devolutiva','Os resultados são explicados de forma compreensível, com espaço para esclarecer dúvidas.'],
  ['Orientações e próximos passos','A devolutiva inclui recomendações, possíveis encaminhamentos e caminhos a partir do que foi identificado.'],
  ['Contato com outros profissionais, quando necessário','Quando pertinente e autorizado, informações de outros profissionais podem contribuir para a avaliação.']
];
const childAssessmentCare = [
  ['Entrevista detalhada com os responsáveis','Conheço a história, o desenvolvimento, as dificuldades atuais e as perguntas que precisam ser respondidas.'],
  ['Avaliação planejada para a criança ou adolescente','Os procedimentos são escolhidos conforme a idade, a história, as características e as questões do caso.'],
  ['Encontros individuais com a criança ou adolescente','Os encontros permitem avaliar o funcionamento e observar como as dificuldades aparecem durante as atividades.'],
  ['Testes e instrumentos psicológicos','São utilizados instrumentos adequados à idade e às questões investigadas.'],
  ['Avaliação do funcionamento cognitivo','Conforme a necessidade, são avaliados raciocínio, atenção, memória, aprendizagem, linguagem e funções executivas.'],
  ['Avaliação emocional e comportamental','Emoções, comportamento, personalidade, interação social e repercussões no cotidiano também podem ser investigados.'],
  ['Informações de diferentes contextos','Relatos, documentos, questionários e informações da escola ou de outros profissionais podem contribuir quando pertinentes e autorizados.'],
  ['Análise integrada dos resultados','As informações são analisadas em conjunto e relacionadas à história e ao funcionamento da criança ou adolescente.'],
  ['Investigação e diferenciação de hipóteses','Diferentes explicações possíveis são consideradas para construir conclusões bem fundamentadas.'],
  ['Laudo neuropsicológico','Os responsáveis recebem um laudo organizado e compreensível para a família, a escola e outros profissionais de saúde.'],
  ['Devolutiva aos responsáveis','Os resultados e as conclusões são explicados em uma sessão com espaço para dúvidas.'],
  ['Orientações para família e escola','As orientações consideram as necessidades identificadas e como elas aparecem nos diferentes contextos.'],
  ['Encaminhamentos e próximos passos','Quando necessário, são indicados cuidados, adaptações ou profissionais que podem contribuir depois da avaliação.'],
  ['Documentação para acesso a direitos','Quando aplicável, o laudo pode compor a documentação necessária para solicitar direitos, identificações, adaptações ou benefícios. Também pode oferecer informações para a avaliação diagnóstica de médicos e outros profissionais.']
];
const earlyAssessmentCare = [
  ['Entrevista detalhada com os responsáveis','Conversamos sobre a história da criança, seu desenvolvimento, saúde, comportamento, rotina, relações e as preocupações que motivaram a avaliação.'],
  ['Avaliação individualizada do desenvolvimento','Os procedimentos são escolhidos de acordo com a idade, o momento do desenvolvimento e as questões que precisam ser esclarecidas.'],
  ['Observação clínica da criança','A forma como a criança brinca, se comunica, interage, explora o ambiente e responde às situações também fornece informações importantes sobre seu desenvolvimento.'],
  ['Avaliação de diferentes áreas do desenvolvimento','São investigados aspectos como cognição e aprendizagem inicial, linguagem e comunicação, desenvolvimento motor, interação social, comportamento e regulação emocional, conforme a necessidade do caso.'],
  ['Instrumentos adequados à primeira infância','Quando pertinentes, são utilizados instrumentos, escalas e questionários apropriados à idade e às questões investigadas.'],
  ['Informações de outros contextos','Quando necessário, informações da escola, de outros cuidadores ou de profissionais que acompanham a criança ajudam a compreender como ela funciona em diferentes ambientes.'],
  ['Análise integrada das informações','História do desenvolvimento, observação clínica, instrumentos e informações de diferentes contextos são analisados em conjunto para construir uma compreensão da criança.'],
  ['Laudo neuropsicológico','A família recebe um laudo com os principais resultados, conclusões e recomendações decorrentes da avaliação.'],
  ['Devolutiva e orientações','Os resultados são explicados aos responsáveis, com espaço para dúvidas, orientações sobre as necessidades identificadas e indicação de próximos passos quando necessário.']
];
const programCare = [
  ['Avaliação inicial das dificuldades executivas','Identificamos como dificuldades de organização, planejamento, tempo, início de tarefas e outras funções aparecem na sua rotina.'],
  ['Objetivos concretos para a intervenção','Definimos quais dificuldades e situações da vida real serão priorizadas durante os encontros.'],
  ['Estratégias personalizadas','Seleciono e adapto estratégias conforme as dificuldades identificadas e a realidade da sua rotina.'],
  ['Ferramentas de organização e planejamento','Você aprende recursos para organizar compromissos, prioridades, tarefas e projetos.'],
  ['Estratégias de manejo do tempo','Trabalhamos estimativa de duração, planejamento do tempo e uso funcional de agenda ou calendário.'],
  ['Estratégias para iniciar e concluir tarefas','As tarefas são divididas em etapas e são construídos apoios para começar, manter e finalizar atividades.'],
  ['Recursos para reduzir esquecimentos e perdas de prazos','São desenvolvidos sistemas simples para registrar, lembrar e acompanhar compromissos e tarefas.'],
  ['Materiais para aplicação no cotidiano','Você recebe materiais e recursos para consultar e utilizar na rotina.'],
  ['Experimentação e análise entre os encontros','As estratégias são testadas em situações reais. Nos encontros seguintes, analisamos o que funcionou, o que não funcionou e quais fatores facilitaram ou dificultaram a aplicação.'],
  ['Ajustes individualizados das estratégias','Os recursos são modificados quando necessário para se tornarem mais funcionais e sustentáveis.'],
  ['Acompanhamento do progresso','Observamos as mudanças, as dificuldades que permanecem e o que ainda precisa ser praticado.'],
  ['Plano de manutenção','Ao final, organizamos como você pode continuar utilizando e ajustando as estratégias depois da intervenção.']
];
const careerCare = [
  ['Entrevistas e compreensão da sua história','Conversamos sobre sua dúvida, trajetória, experiências, contexto de vida e o momento atual para definir o que precisa ser esclarecido.'],
  ['Interesses, habilidades e características pessoais','Investigamos interesses, recursos, preferências e características importantes para suas escolhas profissionais.'],
  ['Valores e prioridades','Refletimos sobre o que importa para você e quais aspectos precisam ser considerados na decisão.'],
  ['Testes de personalidade e interesses profissionais','Testes psicológicos de personalidade e interesses profissionais fazem parte do processo e ampliam as informações disponíveis para a escolha.'],
  ['Reflexões e barreiras à escolha','Perguntas e atividades ajudam a organizar as possibilidades e trabalhar medo de errar, insegurança, expectativas familiares, autoexigência e outras questões que interfiram na decisão.'],
  ['Pesquisa acompanhada das possibilidades','Pesquisamos juntos cursos, profissões, áreas ou caminhos de carreira. Também posso orientar e sugerir pesquisas entre os encontros, ajudando a reunir e compreender as informações.'],
  ['Análise considerando sua realidade','As possibilidades são examinadas levando em conta seu contexto, recursos, limites, prioridades e momento de vida.'],
  ['Construção de critérios para a decisão','Construímos critérios próprios para comparar alternativas e tomar uma decisão mais consciente e fundamentada.'],
  ['Devolutiva e síntese das alternativas','Ao final, conversamos sobre o que foi compreendido e organizamos as possibilidades e os critérios construídos ao longo do processo.'],
  ['Relatório psicológico e próximos passos','Você recebe um relatório psicológico com a síntese do processo, resultados, orientações, recomendações e próximos passos.']
];

const pages = {
  'psicoterapia-adultos':{eyebrow:'Psicoterapia',title:'Psicoterapia para adultos',lead:'Um espaço de cuidado para compreender o que está acontecendo, enfrentar momentos difíceis e construir mudanças possíveis. Atendimento presencial em Taquara/RS ou online.',care:{title:'O que você pode esperar do acompanhamento',items:adultTherapyCare},principles:adultTherapyPrinciples,principlesBeforeLast:true,sections:[
    ['Um processo para compreender o que está acontecendo e construir mudanças possíveis.','O trabalho acompanha questões do desenvolvimento humano em diferentes fases da vida. Você não precisa ter um diagnóstico nem chegar sabendo explicar tudo: o ponto de partida pode ser uma dificuldade prática, uma transição, um objetivo de mudança ou o desejo de viver de forma mais coerente com o que importa.'],
    ['Questões que podem ser trabalhadas',['ansiedade, tristeza, estresse, irritabilidade e sobrecarga','luto, traumas, divórcio, mudanças familiares e outras transições','relações afetivas, familiares, sociais e profissionais','gênero e sexualidade','identidade, autoestima, autonomia, limites e formas de se posicionar','estudos, trabalho, aprendizagem, atenção, organização e hábitos','parentalidade e relações de cuidado','regulação emocional, tomada de decisões e mudança de comportamentos','impactos do TDAH, do autismo e de outras condições do desenvolvimento ou da saúde mental','desenvolvimento pessoal, valores, qualidade de vida e novas possibilidades']],
    ['Abordagens utilizadas','Minha atuação é orientada principalmente pela Terapia do Esquema e pela Terapia de Aceitação e Compromisso, ACT, com contribuições da Terapia Cognitivo-Comportamental, TCC. Os recursos são escolhidos conforme as necessidades de cada pessoa e os objetivos do acompanhamento.'],
    ['Avaliação clínica não é avaliação neuropsicológica','A compreensão inicial faz parte da psicoterapia. Quando uma pergunta exige investigação cognitiva ampla, aplicação extensa de testes e elaboração de laudo, a avaliação neuropsicológica é discutida separadamente.']
  ],pricing:adultTherapyPricing,mode:'Presencial em Taquara ou online'},

  'psicoterapia-criancas-adolescentes':{eyebrow:'Psicoterapia',title:'Psicoterapia para crianças e adolescentes',lead:'Um processo de cuidado adequado à fase do desenvolvimento, com cuidado psicológico para a criança ou adolescente e participação dos responsáveis ao longo do acompanhamento. Atendimento presencial em Taquara/RS a partir de 3 anos e online a partir de 10 anos.',care:{title:'O que você pode esperar do acompanhamento',intro:'Um processo que considera a criança em seu contexto.',items:childTherapyCare},principles:childTherapyPrinciples,principlesBeforeLast:true,sections:[
    ['Questões que podem ser trabalhadas',['ansiedade, medos e insegurança','tristeza, estresse, irritabilidade e mudanças de humor','dificuldade para reconhecer e regular emoções','impactos emocionais de experiências e dificuldades vividas','autoestima e autoconfiança','conflitos familiares','dificuldades nas relações escolares ou com colegas','dificuldades de aprendizagem e desempenho escolar','atenção, rotina, organização e construção de hábitos','impulsividade, baixa tolerância à frustração e dificuldades de comportamento','luto, traumas, divórcio dos pais e outras mudanças familiares','impactos do TDAH, do autismo e de outras condições do desenvolvimento','autonomia e habilidades sociais']],
    ['Como começa e como os responsáveis participam','A primeira sessão é realizada somente com os pais ou responsáveis. Depois começam os encontros com a criança ou adolescente. A frequência e o formato dos contatos com os responsáveis são definidos conforme a idade e as necessidades do caso, preservando o espaço terapêutico da criança ou do adolescente.'],
    ['Psicoterapia não é avaliação neuropsicológica','A compreensão inicial faz parte do cuidado e considera informações da família e, quando pertinente, da escola. Quando a questão exige investigação cognitiva ampla, testes e laudo, a avaliação neuropsicológica é discutida separadamente.']
  ],pricing:childTherapyPricing,mode:'Presencial a partir de 3 anos · online a partir de 10 anos'},

  'avaliacao-adultos':{eyebrow:'Avaliação neuropsicológica',title:'Avaliação neuropsicológica de adultos',lead:'Investigação individualizada para compreender como aspectos cognitivos, emocionais, comportamentais e do desenvolvimento aparecem na vida cotidiana. O planejamento considera as perguntas do caso, a idade, a história e as informações que aparecem ao longo do processo.',care:{title:'O que você recebe',items:adultAssessmentCare},sections:[
    ['O que costuma ser investigado',['histórico do desenvolvimento e histórico médico','raciocínio e funcionamento intelectual','atenção e concentração','memória e aprendizagem','planejamento, organização, controle dos impulsos e flexibilidade','linguagem e comunicação','aspectos emocionais, comportamentais e de personalidade','interação social e desenvolvimento','autonomia e funcionamento cotidiano']],
    ['Etapas do processo',['Entrevista e definição das perguntas da avaliação','Investigação com testes, instrumentos e outras fontes de informação','Análise integrada e elaboração do laudo neuropsicológico','Devolutiva para explicar resultados e próximos passos'],'numbered'],
    ['Avaliação online','Pode ser realizada com adultos entre 18 e 50 anos quando a demanda e os instrumentos permitirem. Não realizo online investigação de altas habilidades/superdotação ou deficiência intelectual. A adequação da modalidade é avaliada antes do início.']
  ],pricing:assessmentPricing,mode:'Presencial ou online'},

  'avaliacao-criancas-adolescentes':{eyebrow:'Avaliação neuropsicológica',title:'Avaliação neuropsicológica de crianças e adolescentes',lead:'Investigação individualizada para compreender desenvolvimento, aprendizagem, atenção, memória, emoções e comportamento.',care:{title:'O que você recebe',intro:'O planejamento considera as perguntas do caso, a idade, a história e as informações que aparecem ao longo do processo.',items:childAssessmentCare},sections:[
    ['O que costuma ser investigado',['raciocínio e funcionamento intelectual','atenção, concentração, memória e aprendizagem','linguagem e comunicação','planejamento, organização, controle dos impulsos e flexibilidade','desenvolvimento emocional, comportamento e personalidade','interação social, autonomia e funcionamento cotidiano','repercussões em casa, na escola e nas relações']],
    ['Etapas do processo',['Entrevista inicial com os responsáveis','Encontros com a criança ou adolescente','Uma sessão de questionários com os responsáveis e, algumas vezes, uma segunda sessão','Escola e outros contextos, quando pertinente','Integração das informações e elaboração do laudo neuropsicológico','Devolutiva com os responsáveis'],'numbered']
  ],pricing:assessmentPricing,mode:'Atendimento presencial'},

  'avaliacao-bebes-criancas-pequenas':{eyebrow:'Avaliação do desenvolvimento',title:'Avaliação de bebês e crianças pequenas',lead:'Uma avaliação individualizada do desenvolvimento, da linguagem, da motricidade, da aprendizagem inicial, das emoções, do comportamento e da interação social.',care:{title:'O que você recebe',intro:'A avaliação de crianças pequenas exige um olhar clínico experiente. Como nessa fase existem menos possibilidades de uso de testes padronizados, a avaliação clínica, as atividades propostas, o manejo e a observação cuidadosa da criança durante os encontros ganham ainda mais importância.',items:earlyAssessmentCare},sections:[
    ['Como o processo acontece','A avaliação ocorre em oito encontros: quatro com a criança e quatro com os responsáveis. Com a criança, são realizadas atividades, tarefas e procedimentos adequados à idade para avaliar as diferentes áreas do desenvolvimento. Com os responsáveis, são realizadas a entrevista inicial sobre a história e o desenvolvimento da criança, duas sessões para aplicação de questionários desenvolvidos para serem respondidos por pais ou responsáveis e aprofundamento das informações, além da sessão de devolutiva. Quando pertinente, também pode ser realizado contato ou reunião com a escola.'],
    ['A observação clínica também faz parte da avaliação',['como a criança entra no ambiente e se separa dos responsáveis','se chora, como se acalma e quando procura os pais','interação, comunicação, resposta ao nome e a instruções','como pede ajuda e comunica o que deseja','atenção compartilhada, imitação e iniciativa de interação','manutenção da interação e resposta a novidades, mudanças e interrupções','espera, frustração, limites e recuperação','autonomia e resolução espontânea de problemas','caminhada, equilíbrio, coordenação e exploração do ambiente']],
    ['O brincar também faz parte da avaliação',['como utiliza e explora os brinquedos','uso funcional e possíveis usos repetitivos dos objetos','brincadeira simbólica e de faz de conta','variedade, criatividade e flexibilidade','brincadeira compartilhada e inclusão de outra pessoa na atividade']]
  ],pricing:earlyAssessmentPricing,mode:'Atendimento presencial'},

  'acompanhamento-tdah':{eyebrow:'Psicoterapia e TDAH',title:'Psicoterapia para pessoas com TDAH',lead:'Psicoterapia especializada que considera emoções, relações, autoestima e as repercussões do TDAH na vida cotidiana.',care:{title:'O que você pode esperar do acompanhamento',intro:'O diagnóstico orienta o trabalho, mas não resume a pessoa. As manifestações, a história e as necessidades de cada pessoa são diferentes.',items:tdahTherapyCare},principles:tdahTherapyPrinciples,sections:[
    ['O que pode ser trabalhado',['ansiedade, estresse e sobrecarga','frustração, culpa e autocrítica','impulsividade e regulação emocional','autoestima e impactos de críticas recebidas','relações familiares e afetivas','relações sociais, escolares e profissionais','início e conclusão de tarefas','organização, planejamento e manejo do tempo','rotina, hábitos e responsabilidades','adaptação ao diagnóstico e compreensão do próprio funcionamento']],
    ['O TDAH em diferentes fases da vida',['Na infância, o trabalho pode desenvolver estratégias e apoios precocemente para dificuldades funcionais já presentes.','Na adolescência, ganham espaço autonomia, estudos, organização, relacionamentos, identidade, escolhas e responsabilidades.','Na vida adulta, também podem ser cuidadas consequências acumuladas, como frustrações, críticas, culpa, autocrítica e impactos acadêmicos, profissionais, relacionais e na autoestima.']]
  ],pricing:specializedTherapyPricing,mode:'Psicoterapia individual · presencial ou online'},

  'acompanhamento-autismo':{eyebrow:'Psicoterapia e autismo',title:'Psicoterapia para pessoas autistas',lead:'Psicoterapia especializada que considera emoções, relações, identidade, rotina, sobrecarga, autonomia e necessidades de adaptação em diferentes fases da vida.',care:{title:'O que você pode esperar do acompanhamento',intro:'O diagnóstico orienta o trabalho, mas não resume a pessoa. As manifestações, a história e as necessidades de cada pessoa são diferentes.',items:autismTherapyCare},principles:autismTherapyPrinciples,sections:[
    ['Mudança sem apagar diferenças','É importante distinguir aquilo que precisa ser desenvolvido ou modificado daquilo que pode precisar de compreensão, acomodação, adaptação ou mudança no ambiente.'],
    ['Psicoterapia, com estratégias quando necessário','O foco é psicoterapêutico: cuidar de emoções, experiências, relações e desafios da vida. Recursos práticos podem fazer parte do processo quando forem úteis.']
  ],pricing:specializedTherapyPricing,mode:'Psicoterapia individual · presencial ou online'},

  'organizacao-planejamento-autonomia':{eyebrow:'Intervenção individual especializada',title:'Organização e Planejamento para Adultos com TDAH',lead:'Uma intervenção individual especializada, realizada ao longo de 12 semanas, para desenvolver habilidades de organização, planejamento e manejo do tempo.<br><br>Primeiro compreendemos onde estão suas principais dificuldades e definimos objetivos concretos. A partir disso, seleciono e ensino estratégias, você experimenta os recursos na sua rotina e, nos encontros seguintes, analisamos juntos o que funcionou e o que precisa ser ajustado.<br><br><strong>Duração:</strong> 12 semanas, com 12 encontros individuais de 50 minutos.',care:{title:'O que você recebe',items:programCare},sections:[
    ['Por que são 12 semanas?','Esse período permite aprender, experimentar, observar dificuldades, ajustar estratégias, praticar novamente e consolidar. As tarefas entre todos os encontros são uma parte estrutural da intervenção.'],
    ['Limites deste atendimento','Esta intervenção não é psicoterapia nem avaliação diagnóstica ou neuropsicológica. Também não substitui tratamento médico quando ele for necessário.']
  ],pricing:programPricing,mode:'12 semanas · 12 encontros individuais de 50 minutos'},

  'orientacao-profissional-carreira':{eyebrow:'Escolhas e mudanças',title:'Orientação profissional e de carreira',lead:'Um processo para facilitar escolhas, mudanças e transições profissionais. Ajuda a compreender seus interesses, características pessoais e possibilidades, construindo critérios para decisões sobre estudo, profissão e carreira. O processo é realizado em três a cinco encontros.',care:{title:'O que você recebe',items:careerCare},sections:[
    ['Em diferentes momentos da vida',['primeira escolha profissional','mudança de curso','transição de carreira ou de área','planejamento de carreira','avaliação de uma carreira ou projeto que você já considera seriamente','aposentadoria e construção de novos projetos']],
    ['Um processo construído para cada decisão','O processo é construído de acordo com a dúvida e o momento de cada pessoa. Os recursos utilizados podem variar porque escolher uma primeira profissão, decidir se muda de curso e repensar uma carreira depois de anos de trabalho são questões diferentes.'],
    ['Uma decisão mais consciente e fundamentada','O processo oferece informações, amplia a compreensão sobre você e sobre as possibilidades existentes e ajuda a construir critérios para uma decisão mais consciente e fundamentada.']
  ],pricing:careerPricing,mode:'3 a 5 encontros · atendimento individual'},

  'profissionais':{eyebrow:'Para profissionais e escolas',title:'Encaminhamento e diálogo no cuidado',lead:'Profissionais da saúde e escolas podem encaminhar para psicoterapia, avaliação neuropsicológica e outros serviços de avaliação e intervenção.',sections:[
    ['Serviços para encaminhamento',['psicoterapia para adultos','psicoterapia para crianças e adolescentes','psicoterapia para pessoas com TDAH','psicoterapia para pessoas autistas','avaliação neuropsicológica de adultos','avaliação neuropsicológica de crianças e adolescentes','avaliação de bebês e crianças pequenas','intervenção em organização e planejamento para adultos com TDAH','orientação profissional e de carreira']],
    ['Contribuições de profissionais e da escola','Informações de quem já acompanha a pessoa podem ajudar a compreender como as dificuldades aparecem em diferentes contextos e ao longo do tempo. Com autorização da pessoa atendida ou de seus responsáveis, leio relatórios, atestados e outros documentos e posso realizar entrevista com o profissional ou contato com a escola para integrar essas informações.'],
    ['Comunicação com profissionais e escola','Minha experiência em equipes interdisciplinares influencia a prática atual. Quando pertinente e autorizado, valorizo a comunicação com quem já acompanha a pessoa. Também posso oferecer um retorno ao profissional que encaminhou, respeitando o sigilo e a finalidade combinada.'],
    ['Continuidade do cuidado','O encaminhamento não precisa interromper um acompanhamento já existente. A avaliação neuropsicológica, a orientação profissional e a intervenção em organização e planejamento, por exemplo, podem ser realizadas enquanto a pessoa permanece em psicoterapia com seu profissional de referência.'],
    ['Quando encaminhar para avaliação neuropsicológica',['quando é necessário compreender dificuldades cognitivas, comportamentais ou do desenvolvimento','para investigar hipóteses diagnósticas e diagnósticos diferenciais','quando dificuldades permanecem pouco compreendidas','para obter informações que possam orientar tratamento, família ou escola']]
  ],mode:'Encaminhamentos presenciais e online'},

  'sobre':{eyebrow:'Sobre mim',title:'Quem é a Luani?',lead:'Desde pequena, sempre gostei muito de estudar. Tenho curiosidade, gosto de entender como as coisas funcionam e, quando um assunto me interessa, quero conhecê-lo em profundidade. A Psicologia transformou essa curiosidade em uma forma de compreender as pessoas, o desenvolvimento humano e as diferentes maneiras de sentir, aprender, se relacionar e enfrentar a vida.',sectionNav:[['Formação e primeiras experiências','formacao'],['Atuação como psicóloga','atuacao'],['Meu jeito de trabalhar','jeito-de-trabalhar'],['Neuropsicologia','neuropsicologia'],['Experiência atual','experiencia-atual'],['Formação e qualificações','qualificacoes']],sections:[
    ['Uma formação vivida na prática',['Sou natural de Caxias do Sul e me graduei em Psicologia pela UCS. Durante a faculdade, fui bolsista do ProUni e conciliei os estudos com o trabalho. Mesmo com uma rotina intensa, procurei aproveitar tudo o que a graduação poderia me oferecer. Participei de estágios com atendimento direto, atividades voluntárias, monitorias, pesquisa e trabalhos interdisciplinares. Queria aprender na prática, estar próxima das pessoas e conhecer diferentes possibilidades de atuação da Psicologia.'],'paragraphs','formacao'],
    ['Experiências que começaram ainda na graduação',['O Primeira Infância Melhor foi um dos trabalhos de que mais gostei. Eu acompanhava crianças pequenas e suas famílias, avaliava como estava o desenvolvimento em relação ao esperado para a idade e planejava atividades para ajudá-las a avançar. Era um trabalho próximo, construído dentro da realidade de cada família.','Foi ali que comecei a aprender de verdade sobre desenvolvimento infantil, avaliação do desenvolvimento e intervenção precoce. Também aprendi a observar com cuidado, valorizar pequenas mudanças e compreender que o desenvolvimento de uma criança não acontece separado das relações, das oportunidades e do ambiente em que ela vive. Guardo muito carinho por essa experiência, e o que aprendi nela continua presente no meu trabalho.','A inclusão também atravessou uma parte importante da minha formação. Ainda no início da graduação, trabalhei como monitora de estudantes com deficiência durante o turno escolar. Mais tarde, atuei por mais de três anos como educadora social com crianças e adolescentes autistas e com outras deficiências. Eu realizava atividades individuais e em grupo e trabalhava o desenvolvimento de habilidades e da autonomia.','A convivência cotidiana me ensinou coisas que não poderiam ser aprendidas apenas nos livros. Aprendi que duas pessoas com o mesmo diagnóstico têm formas muito diferentes de se comunicar, aprender, participar e precisar de apoio. Também aprendi que o ambiente pode facilitar o desenvolvimento ou criar novas barreiras.','Durante vários semestres, fui monitora, especialmente na área de neurociências, que sempre despertou muito o meu interesse. Também fui bolsista de iniciação científica por quase dois anos em um grupo de pesquisa de um programa de pós-graduação dedicado à educação especial e à inclusão. Participei de estudos, produção de artigos, eventos científicos e desenvolvimento de materiais educacionais.','Essas experiências foram se conectando. De um lado, eu aprendia a pesquisar. De outro, acompanhava crianças, adolescentes e famílias em situações reais. Aos poucos, fui construindo um olhar que procura aproximar o conhecimento científico da vida cotidiana.'],'paragraphs'],
    ['Quando comecei a trabalhar como psicóloga',['Concluí a graduação no início de 2019 e comecei a trabalhar logo depois. Antes mesmo de me formar, participei de processos seletivos para residências multiprofissionais. Eu havia estudado muito e tenho orgulho dessa aprovação.','Na residência, vivi intensamente a saúde coletiva e o trabalho interdisciplinar. Logo precisei interrompê-la para assumir o cargo de psicóloga para o qual havia sido nomeada em concurso público. Essa foi outra conquista construída com muito estudo e dedicação.','Meus primeiros anos no serviço público foram no CAPSij — Centro de Atenção Psicossocial Infantojuvenil. Eu trabalhava com crianças, adolescentes e famílias em situações de sofrimento psíquico intenso e maior complexidade. Gostava muito daquele trabalho. O fazer clínico era construído em equipe. Os casos eram discutidos por profissionais de diferentes áreas, e precisávamos olhar para muito além do diagnóstico. Era necessário compreender aquela criança ou aquele adolescente, sua família, sua realidade, os riscos presentes e o cuidado possível naquele momento.','Depois, atuei em um serviço especializado no atendimento a crianças e adolescentes vítimas de violências. Era um trabalho voltado à intervenção no trauma, à proteção e à garantia de direitos. Tanto o trabalho no CAPSij quanto no APOIAR aprofundaram minha capacidade de conduzir situações delicadas e identificar quando outros profissionais, serviços ou a rede precisam participar do cuidado.','Em outro momento, trabalhei em Unidades Básicas de Saúde, principalmente no atendimento psicológico de adultos e idosos. Ali, acompanhei outras fases da vida e diferentes formas de sofrimento. Também conheci mais de perto como questões emocionais, familiares, sociais e de saúde podem se entrelaçar na vida de uma pessoa.','Gostei muito de todos esses trabalhos. Cada um me ensinou de uma forma diferente. Juntos, eles ampliaram meu olhar sobre as muitas formas pelas quais o cuidado psicológico pode acontecer.'],'paragraphs','atuacao'],
    ['Um jeito de trabalhar que também foi se transformando',['Logo após a formatura, comecei a atender em psicoterapia na abordagem psicanalítica, que foi muito importante para construir uma escuta profunda, atenta à história, às relações e ao modo como experiências anteriores continuam influenciando a vida atual.','Quando conheci a Terapia do Esquema, algumas técnicas me encantaram, especialmente aquelas que permitem acessar informações profundas e trabalhar traumas e experiências que ainda doem, trazendo para dentro da terapia experiências de acolhimento, proteção e compreensão. Assim, concluí minha formação em Terapia do Esquema em 2023.','Mais tarde, fui me aproximando da Terapia de Aceitação e Compromisso. Encontrei nela uma forma de trabalhar valores, flexibilidade e ações que aproximem a pessoa da vida que deseja construir, inclusive quando algumas experiências precisam de aceitação, adaptação ou de uma maneira diferente de serem vividas.','A Terapia Cognitivo-Comportamental complementou esse trabalho com recursos para compreender cada caso, acompanhar objetivos, desenvolver habilidades e lidar com dificuldades concretas do cotidiano. Meu modo de trabalhar foi se tornando mais ativo, sem perder a profundidade da escuta que construí no início da minha trajetória.'],'paragraphs','jeito-de-trabalhar'],
    ['Da psicopatologia à neuropsicologia',['Desde a graduação, sempre gostei de estudar psicopatologia. Eu queria compreender os diferentes quadros, como os sintomas apareciam, o que diferenciava um do outro e o que poderia explicar determinado sofrimento. Esse interesse sempre esteve presente na psicoterapia e na maneira como penso e estudo cada caso.','A neuropsicologia ampliou esse caminho. Ela acrescentou instrumentos e métodos que ajudam a investigar de forma mais estruturada o funcionamento cognitivo, emocional e comportamental. As avaliações neuropsicológicas passaram a fazer parte da minha atuação em 2025 como uma continuidade dos meus interesses por desenvolvimento humano.','As experiências que tive antes da neuropsicologia influenciam diretamente a forma como avalio hoje. Não analiso apenas os resultados dos testes. Mantenho o olhar atento a como a pessoa compreende as tarefas, se comunica, aprende, reage às dificuldades e resolve problemas. Observo como ela faz, não apenas onde ela chega.'],'paragraphs','neuropsicologia'],
    ['O trabalho que construí ao longo dessa trajetória',['Atuo como psicóloga desde 2019. Minha trajetória reúne mais de 13 mil horas de atendimento e mais de 730 pessoas atendidas. O contato com tantas histórias e formas diferentes de viver, aprender, se relacionar e enfrentar dificuldades reforçou em mim a importância de compreender cada pessoa de maneira individualizada.','Em 2023, com a mudança de cidade, escolhi me dedicar exclusivamente ao atendimento particular. Queria ter mais tempo para pensar cada pessoa, estudar os casos e cuidar da qualidade de cada processo.','Meu trabalho não acontece apenas durante os minutos da sessão. Estudo os casos, integro informações e preparo intervenções e materiais quando necessário. Gosto de compreender profundamente o que está acontecendo, mas não apenas por compreender. Quero que essa compreensão ajude a construir mudanças, estratégias e possibilidades concretas de cuidado e transformação.'],'paragraphs','experiencia-atual']
  ],qualifications:[['Psicologia','Graduação pela Universidade de Caxias do Sul (UCS), concluída em 2019'],['Psicologia Clínica','Especialização concluída em 2023'],['Terapia do Esquema','Formação concluída em 2023'],['Neuropsicologia','Especialização concluída em 2025']],mode:'Psicóloga e Neuropsicóloga · CRP 07/30072'}
};

const path = location.pathname.replace(/^\/+|\/+$/g,'');
const whatsapp = message => 'https://wa.me/5554981514108?text=' + encodeURIComponent(message);
const onlineCalendar = 'https://calendar.app.google/4RRc1sFWevkYAi8M7';
const scheduling = {
  'psicoterapia-adultos':{service:'psicoterapia para adultos',presencial:'Agendar psicoterapia presencial',online:'Agendar psicoterapia online'},
  'psicoterapia-criancas-adolescentes':{service:'psicoterapia para criança ou adolescente',presencial:'Agendar psicoterapia presencial',online:'Agendar psicoterapia online'},
  'avaliacao-adultos':{service:'avaliação neuropsicológica de adulto',presencial:'Agendar avaliação presencial',online:'Agendar avaliação online'},
  'avaliacao-criancas-adolescentes':{service:'avaliação neuropsicológica de criança ou adolescente',presencial:'Agendar avaliação presencial'},
  'avaliacao-bebes-criancas-pequenas':{service:'avaliação de bebê ou criança pequena',presencial:'Agendar avaliação presencial'},
  'acompanhamento-tdah':{service:'psicoterapia para pessoa com TDAH',presencial:'Agendar psicoterapia presencial',online:'Agendar psicoterapia online'},
  'acompanhamento-autismo':{service:'psicoterapia para pessoa autista',presencial:'Agendar psicoterapia presencial',online:'Agendar psicoterapia online'},
  'organizacao-planejamento-autonomia':{service:'Organização e Planejamento para Adultos com TDAH',presencial:'Agendar atendimento presencial',online:'Agendar atendimento online'},
  'orientacao-profissional-carreira':{service:'orientação profissional e de carreira',presencial:'Solicitar orçamento pelo WhatsApp',whatsappMessage:'Olá, Luani. Encontrei seu site e gostaria de conversar sobre a orientação profissional e de carreira e receber uma estimativa do número de encontros e do investimento total.'}
};

function header(){return `<header class="site-header"><nav class="nav" aria-label="Navegação principal"><a class="brand" href="/"><span class="monogram">LP</span><span class="brand-copy"><span class="brand-name">Luani dos Santos Paim</span><span class="brand-sub">Psicóloga e Neuropsicóloga · CRP 07/30072</span></span></a><button class="menu-button" aria-expanded="false" aria-controls="nav-links">Menu</button><div class="nav-links" id="nav-links"><a href="/#servicos">Serviços</a><a href="/profissionais/">Para profissionais e escolas</a><a href="/sobre/">Sobre mim</a></div><a class="nav-cta" href="/agendamento/">Agendar</a></nav></header>`}
function footer(){return `<footer class="site-footer"><div class="footer-inner"><div><h3>Luani dos Santos Paim</h3><p>Psicóloga e Neuropsicóloga · CRP 07/30072<br>Mente Viva Psicologia e Neuropsicologia</p></div><div class="footer-contact"><p>Rua General Emílio Lúcio Esteves, 1131, sala 308, Taquara/RS</p><a href="mailto:psicologaluanipaim@gmail.com">psicologaluanipaim@gmail.com</a><a href="tel:+5554981514108">(54) 98151-4108</a></div><div><h3>Informações</h3><a href="/agendamento/">Contato e agendamento</a><a href="/privacidade/">Política de privacidade</a><a href="/termos/">Termos de uso</a></div></div></footer>`}
function card(item){return `<a class="card" href="/${item.slug}/"><div class="status">${item.mode}</div><h3>${item.title}</h3><p>${item.short}</p><span>Ver informações, valores e agendar</span></a>`}
function home(){return `${header()}<main><section class="hero"><div><div class="eyebrow">Psicologia clínica e neuropsicologia</div><h1>Cuidado psicológico para compreender e transformar.</h1><div class="home-modes" aria-label="Opções de agendamento"><a class="home-mode-button primary" target="_blank" rel="noopener" href="${whatsapp('Olá, Luani. Encontrei seu site e gostaria de agendar um atendimento presencial em Taquara.')}"><strong>Agendar atendimento presencial</strong><small>Em Taquara/RS · continuar pelo WhatsApp</small></a><a class="home-mode-button secondary" target="_blank" rel="noopener" href="${onlineCalendar}"><strong>Agendar atendimento online</strong><small>Escolher um horário no calendário</small></a></div></div><figure class="hero-portrait"><img src="/assets/luani-home.jpg" alt="Luani dos Santos Paim, psicóloga e neuropsicóloga" width="1200" height="1200"><figcaption><span>Luani dos Santos Paim</span><small>Psicóloga e Neuropsicóloga · CRP 07/30072</small></figcaption></figure></section><section class="services" id="servicos"><div class="section-head"><h2>Serviços</h2></div>${services.map(g=>`<div class="service-group"><div class="group-label">${g.group}</div><div class="card-grid">${g.items.map(card).join('')}</div></div>`).join('')}</section><section class="wide-cta"><div class="wide-cta-inner"><div><h2>Não tem certeza sobre qual é o melhor atendimento para você?</h2><p>A conversa inicial dura 20 minutos, acontece online e serve para você me conhecer e tirar suas dúvidas.</p></div><a class="button" href="/conversa-inicial/">Entender a conversa inicial</a></div></section></main>${footer()}`}
function renderSection(s){const [title,body,type,id]=s;let content='';if(type==='numbered')content=`<div class="steps">${body.map((x,i)=>`<div class="step"><b>${i+1}</b><span>${x}</span></div>`).join('')}</div>`;else if(type==='paragraphs')content=body.map(x=>`<p>${x}</p>`).join('');else if(Array.isArray(body))content=`<ul>${body.map(x=>`<li>${x}</li>`).join('')}</ul>`;else content=`<p>${body}</p>`;return `<section${id?` id="${id}"`:''}><h2>${title}</h2>${content}</section>`}
function renderCare(care){if(!care)return '';return `<section class="care-included"><div class="care-intro"><div class="eyebrow">Atendimento individualizado</div><h2>${care.title}</h2>${care.intro?`<p>${care.intro}</p>`:''}</div><div class="care-grid">${care.items.map(([itemTitle,text],i)=>`<article class="care-item"><b>${String(i+1).padStart(2,'0')}</b><div><h3>${itemTitle}</h3><p>${text}</p></div></article>`).join('')}</div></section>`}
function renderPrinciples(items){if(!items)return '';return `<section class="principles"><h2>Princípios que orientam meu trabalho</h2><div class="principles-grid">${items.map(([title,text])=>`<article class="principle-item"><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>`}
function renderServiceContent(data){const split=data.principles?(data.principlesBeforeLast?Math.max(0,data.sections.length-1):data.sections.length):data.sections.length;const before=data.sections.slice(0,split).map(renderSection).join('');const after=data.sections.slice(split).map(renderSection).join('');return `<article class="prose">${before}${renderPrinciples(data.principles)}${after}</article>`}
function renderPricing(pricing){if(!pricing)return '';return `<section class="pricing service-pricing" id="valores"><div class="eyebrow">${pricing.eyebrow}</div><h2>${pricing.title}</h2><p class="pricing-intro">${pricing.intro}</p><div class="pricing-options">${pricing.options.map(option=>`<div class="price-option"><h3>${option[0]}</h3><strong>${option[1]}</strong><p>${option[2]}</p></div>`).join('')}</div>${pricing.note?`<p class="pricing-note">${pricing.note}</p>`:''}${pricing.reimbursement?`<div class="reimbursement"><strong>Atendimento particular e reembolso</strong><p>${pricing.reimbursement}</p></div>`:''}</section>`}
function renderQualifications(items){if(!items)return '';return `<section class="qualifications" id="qualificacoes"><h2>Formação e qualificações</h2><div class="qualification-grid">${items.map(([title,text])=>`<div><h3>${title}</h3><p>${text}</p></div>`).join('')}</div></section>`}
function renderSectionNav(items){if(!items)return '';return `<nav class="section-nav" aria-label="Navegação desta página">${items.map(([label,id])=>`<a href="#${id}">${label}</a>`).join('')}</nav>`}
function renderActions(data){const config=scheduling[path];if(path==='profissionais')return `<section class="direct-actions compact"><div class="status">${data.mode}</div><h2>Fazer um encaminhamento</h2><p>Envie uma mensagem informando o serviço procurado. A troca de informações clínicas será combinada depois, pelos canais adequados e com autorização.</p><a class="button primary" target="_blank" rel="noopener" href="${whatsapp('Olá, Luani. Sou profissional ou representante de uma escola e gostaria de conversar sobre um encaminhamento.')}">Falar com Luani pelo WhatsApp</a></section>`;if(path==='sobre')return `<section class="direct-actions compact"><div class="status">${data.mode}</div><h2>Conheça os atendimentos</h2><a class="button primary" href="/#servicos">Ver todos os serviços</a></section>`;if(path==='orientacao-profissional-carreira')return `<section class="direct-actions compact"><div class="status">${data.mode}</div><h2>Solicite uma estimativa</h2><p>Conte brevemente o que você procura para receber uma estimativa do número de encontros e do investimento total.</p><a class="button primary" target="_blank" rel="noopener" href="${whatsapp(config.whatsappMessage)}">Conversar pelo WhatsApp</a></section>`;if(!config)return '';const presencial=config.presencial?`<a class="booking-option" target="_blank" rel="noopener" href="${whatsapp(config.whatsappMessage||`Olá, Luani. Encontrei seu site e gostaria de agendar ${config.service} na modalidade presencial.`)}"><span>${config.presencial}</span><small>Continuar pelo WhatsApp</small></a>`:'';const online=config.online?`<a class="booking-option" target="_blank" rel="noopener" href="${onlineCalendar}"><span>${config.online}</span><small>Escolher um horário no calendário</small></a>`:'';return `<section class="direct-actions"><div class="status">${data.mode}</div><h2>Agende por aqui</h2><p>Escolha a modalidade para seguir diretamente ao agendamento.</p><div class="booking-options">${presencial}${online}</div><a class="unsure-link" href="/conversa-inicial/">Ainda não tenho certeza se este serviço é para mim</a></section>`}
function quickValueLink(data){if(!data.pricing)return '';const therapy=['psicoterapia-adultos','psicoterapia-criancas-adolescentes','acompanhamento-tdah','acompanhamento-autismo'].includes(path);return `<a class="quick-value-link" href="#valores">${therapy?'Ver frequência e valores':'Ver investimento'}</a>`}
function renderMobileBooking(data){const config=scheduling[path];if(!data.pricing||!config)return '';const links=[];if(config.presencial){const label=config.online?'Presencial':path==='orientacao-profissional-carreira'?'Orçamento':'Agendar';links.push(`<a class="mobile-booking-primary" target="_blank" rel="noopener" href="${whatsapp(config.whatsappMessage||`Olá, Luani. Encontrei seu site e gostaria de agendar ${config.service} na modalidade presencial.`)}">${label}</a>`)}if(config.online)links.push(`<a class="mobile-booking-primary" target="_blank" rel="noopener" href="${onlineCalendar}">Online</a>`);links.push('<a href="#valores">Valores</a>');return `<nav class="mobile-booking-bar" aria-label="Atalhos para agendamento">${links.join('')}</nav>`}
function servicePage(data){const valueLink=quickValueLink(data);const pageHero=path==='sobre'?`<div class="page-hero about-hero"><div><div class="eyebrow">${data.eyebrow}</div><h1>${data.title}</h1><p class="lead">${data.lead}</p></div><figure class="about-portrait"><img src="/assets/luani-sobre.jpg" alt="Retrato de Luani dos Santos Paim" width="900" height="1080"></figure></div>`:`<div class="page-hero"><div class="eyebrow">${data.eyebrow}</div><h1>${data.title}</h1><p class="lead">${data.lead}</p>${valueLink}</div>`;return `${header()}<main>${pageHero}<div class="service-layout"><div class="service-main">${renderSectionNav(data.sectionNav)}${renderCare(data.care)}${renderServiceContent(data)}${renderQualifications(data.qualifications)}</div><aside class="booking-sidebar">${renderActions(data)}</aside>${renderPricing(data.pricing)}</div></main>${footer()}${renderMobileBooking(data)}`}
function booking(){return `${header()}<main><div class="page-hero"><div class="eyebrow">Contato e agendamento</div><h1>Como você prefere ser atendido?</h1><p class="lead">Escolha a opção mais próxima do que você procura e siga diretamente para o agendamento.</p><div class="choice-grid"><div class="choice"><div class="status">Presencial</div><h3>Atendimento em Taquara</h3><p>Envie uma mensagem para verificar a indicação do serviço e os horários presenciais disponíveis.</p><a class="button primary" target="_blank" rel="noopener" href="${whatsapp('Olá, Luani. Encontrei seu site e gostaria de agendar um atendimento presencial em Taquara.')}">Agendar pelo WhatsApp</a></div><div class="choice"><div class="status">Online</div><h3>Atendimento online</h3><p>Consulte os horários disponíveis e faça o agendamento diretamente no calendário.</p><a class="button primary" target="_blank" rel="noopener" href="${onlineCalendar}">Escolher horário online</a></div><div class="choice"><div class="status">Ainda não sei</div><h3>Tenho dúvida sobre o serviço</h3><p>Veja como funciona a conversa inicial breve antes de decidir se deseja agendar.</p><a class="button secondary" href="/conversa-inicial/">Entender a conversa inicial</a></div></div><p class="contact-note">Se preferir, envie uma mensagem diretamente para <a target="_blank" rel="noopener" href="${whatsapp('Olá, Luani. Encontrei seu site e gostaria de receber informações.')}">(54) 98151-4108</a>.</p></div></main>${footer()}`}
function conversation(){return `${header()}<main><div class="page-hero"><div class="eyebrow">Conversa inicial</div><h1>Quando você ainda não sabe qual serviço procurar</h1><p class="lead">Uma conversa online de 20 minutos para esclarecer diferenças entre os serviços e orientar o próximo passo.</p></div><div class="content"><article class="prose"><h2>Para que serve</h2><p>Ela faz sentido quando você está em dúvida entre psicoterapia, avaliação ou outro acompanhamento, ou quando precisa entender se a modalidade disponível corresponde à sua necessidade.</p><h2>Como funciona</h2><p>A conversa dura 20 minutos e acontece online. Esse tempo é destinado a compreender brevemente a sua dúvida, explicar as diferenças entre os serviços e indicar qual pode ser o próximo passo.</p><h2>O que ela não é</h2><ul><li>não é sessão de psicoterapia gratuita</li><li>não é anamnese ou avaliação</li><li>não produz diagnóstico ou orientação clínica</li><li>não é um canal para situações de urgência</li></ul></article><aside class="aside"><div class="status">20 minutos · online</div><h3>Quer esclarecer sua dúvida?</h3><p>Envie uma mensagem para combinar a conversa inicial.</p><a class="button primary" target="_blank" rel="noopener" href="${whatsapp('Olá, Luani. Encontrei seu site e ainda não tenho certeza de qual serviço procurar. Gostaria de combinar uma conversa inicial online de 20 minutos.')}">Solicitar pelo WhatsApp</a><a class="button secondary" href="/agendamento/">Já sei o que procuro</a></aside></div></main>${footer()}`}
function legal(kind){const privacy=kind==='privacidade';return `${header()}<main><article class="legal"><div class="eyebrow">Informações legais</div><h1>${privacy?'Política de privacidade':'Termos de uso'}</h1>${privacy?'<h2>Dados e contato</h2><p>Este site apresenta informações profissionais e, nesta versão, não coleta dados por formulários. Ao utilizar links externos de contato ou agendamento, aplicam-se também as políticas das respectivas plataformas.</p><h2>Finalidade</h2><p>As informações do site servem para apresentar serviços e modalidades de atendimento. Nenhum conteúdo substitui avaliação individual, diagnóstico ou orientação em situações de urgência.</p>':'<h2>Conteúdo informativo</h2><p>O conteúdo deste site tem caráter informativo e não estabelece relação profissional por si só. O atendimento é iniciado apenas após contato, definição do serviço e combinação das condições aplicáveis.</p><h2>Uso responsável</h2><p>Não há promessa de resultado. A indicação e a modalidade de cada serviço dependem da demanda e das condições técnicas e éticas de atendimento.</p>'}<p>Luani dos Santos Paim — Psicóloga e Neuropsicóloga — CRP 07/30072.</p></article></main>${footer()}`}
let html=path===''?home():pages[path]?servicePage(pages[path]):path==='agendamento'?booking():path==='conversa-inicial'?conversation():path==='privacidade'?legal('privacidade'):path==='termos'?legal('termos'):`${header()}<main><div class="page-hero"><h1>Página não encontrada</h1><p class="lead"><a href="/">Voltar ao início</a></p></div></main>${footer()}`;
document.getElementById('app').innerHTML=html;
const menu=document.querySelector('.menu-button');if(menu)menu.addEventListener('click',()=>{const links=document.querySelector('.nav-links');const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));});
